##########################  DataSet  ################################
dataset: Market
BATCH_SIZE: 32
NUM_INSTANCES: 4
y_length: 256
x_length: 256
n_mean: [0.485, 0.456, 0.406]
n_std: [0.229, 0.224, 0.225]
p_hflip: 0.5
p_rerase: 0.5


n_classes: 751
ROOT_DIR: D:\Projects\KLMIN\logs
query_dir: D:\Projects\KLMIN\data\Market\query\ #/mnt/DATADISK/Datasets/vehicle/VeRi/image_query/ #
teste_dir: D:\Projects\KLMIN\data\Market\bounding_box_test\  #/mnt/DATADISK/Datasets/vehicle/VeRi/image_test/ #
train_dir: D:\Projects\KLMIN\data\Market\bounding_box_train\ #/mnt/DATADISK/Datasets/vehicle/VeRi/image_train/ #
query_list_file: D:\Projects\KLMIN\data\veri\name_query.txt
gallery_list_file: D:\Projects\KLMIN\data\veri\name_test.txt
train_list_file: D:\Projects\KLMIN\data\veri\name_train.txt
test_keypoint: D:\Projects\KLMIN\dataset\VeRi\keypoint_orient_test.txt
train_keypoint: D:\Projects\KLMIN\dataset\VeRi\keypoint_orient_train.txt
num_workers_train: 4
num_workers_teste: 6


##########################  Model  ################################
model_arch: 4B
LAI: True
n_cams: 8
n_views: 6
backbone: ibn


##########################  Loss  ################################
loss_function: hard_mining
### Triplet Loss
metric_loss: fastreidtriplet #Batch_hard_triplet #Batch_hard_triplet #SupCon #RLL
triplet_norm: False
triplet_margin: 0.1
tri_loss:
  - 1.0  # r50
  - 0.4  # bot
  - 0.6  # r50
  - 0.6  # bot

### CE Loss
softmax_loss: torch_ce
label_smoothing: 0.1
ce_loss:
  - 1.0  # r50
  - 0.4  # bot
  - 1.0  # r50
  - 1.0  # bot

mean_losses: False

### circle Loss
circle_softmax: False
margin_circle: 0.35
scale_circle: 8

### constrastive loss
margin_constrastive: 0.5
scale_constrast: 1

## instance loss
margin_instance: 0.1

group_norm: False
pretrain_gropnorm: False
gn_init: kaiming
pretrain_ongroups: True



###GPU Settings
torch_seed: 0
half_precision: True 
parallel: False
gpu: 0,1






### Optimizer
optimizer: Adam
lr: 0.0001
weight_decay:  0.0005
bias_lr_factor: 1
momentum: 0.9

###Scheduler
epoch_freeze_L1toL3: 10
sched_name: Warm_MultiStep
num_epochs: 130
milestones: [40, 70, 100]
gamma: 0.1
warmup_factor: 0.0
warmup_iters: 10
warmup_method: linear
min_lr: 7.75e-5





freeze_triplet_branches: 0
freeze_backbone_warmup: False  ## for circle
branch_layer: 3
validation_period: 10


#####Experiment 
pool: GAP
pool_triplet: GAP
pool_trans: GAP
linear_num: False
re_ranking: True

